// Code generated by mockery v2.42.0. DO NOT EDIT.

package servicemocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// ICurrencyService is an autogenerated mock type for the ICurrencyService type
type ICurrencyService struct {
	mock.Mock
}

// GetCurrency provides a mock function with given fields: ctx
func (_m *ICurrencyService) GetCurrency(ctx context.Context) error {
	ret := _m.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for GetCurrency")
	}

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context) error); ok {
		r0 = rf(ctx)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// NewICurrencyService creates a new instance of ICurrencyService. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewICurrencyService(t interface {
	mock.TestingT
	Cleanup(func())
}) *ICurrencyService {
	mock := &ICurrencyService{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
